language: go
go: 
 - 1.4.3
 - 1.5.4
 - release
 - tip

install:
  - go get github.com/apexskier/httpauth
  - go get github.com/go-ini/ini
  - go get github.com/gorilla/mux
  - go get github.com/hpcloud/tail

script:
 - go test -v ./...
