version: 1.0.{build}
clone_folder: c:\gopath\src\github.com\MetalMichael\azure-csgo-server-manager
environment:
  GOPATH: c:\gopath
before_build:
- ps: >-
    mkdir $Env:GOPATH\bin

    curl https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-windows-amd64.zip -o glide.zip

    7z e glide.zip -y

    mv glide.exe $Env:GOPATH\bin

    $Env:PATH += ";" + $Env:GOPATH + "\bin;c:\go\bin"

    .\install.ps1
build:
  verbosity: minimal
build_script:  
  - ps: >-
    ls
    
    .\make.ps1