version: 1.0.{build}
clone_folder: c:\gopath\src\github.com\MetalMichael\azure-csgo-server-manager
environment:
  GOPATH: c:\gopath
before_build:
  - cmd: >-
    mkdir %GOPATH%\bin
    curl -L https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-windows-amd64.zip -o glide.zip
    7z e glide.zip -y
    mv glide.exe %GOPATH%\bin
    set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
    cd src
    glide install
build:
  verbosity: minimal
build_script:  
  - go build -o ../acgsm.exe